name: SSHTerminal
options:
  bundleIdPrefix: com.daniel
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
packages:
  Citadel:
    url: https://github.com/orlandos-nl/Citadel.git
    from: 0.11.1
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: 1.6.0
targets:
  SSHTerminal:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - SSHTerminal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.daniel.sshterminal
      INFOPLIST_FILE: SSHTerminal/Resources/Info.plist
      SWIFT_VERSION: "6.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SWIFT_STRICT_CONCURRENCY: complete
      ENABLE_USER_SCRIPT_SANDBOXING: YES
    dependencies:
      - sdk: Security.framework
      - package: Citadel
      - package: SwiftTerm
